spring.datasource.url=jdbc:mysql://localhost:3306/lifestyle_products?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Priya@19
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Server Port
server.port=8080

# JWT Configuration
lifestyle.app.jwtSecret======================LifestyleProductsSecretKeyJWT2026===================
lifestyle.app.jwtExpirationMs=3600000

# Razorpay Configuration (Test Mode)
razorpay.key.id=rzp_test_TLKKx1wzFP5anv
razorpay.key.secret=5cahiulX4jogIDzsTE0GNe3r